#!/bin/bash
set -e

. "$(dirname -- "$0")/_/husky.sh"

message=$(cat "$1")

if [[ ! $message =~ ^(feature: |fix: ).*$ ]]; then
  echo "\033[31m✖ 请使用正确的message格式，参考：\033[0m"
  echo "\033[32m  ꔷ [jira-id/no-jira] feature: description  \033[0m"
  echo "\033[32m  ꔷ [jira-id/no-jira] chore: description  \033[0m"
  echo "\033[32m  ꔷ [jira-id/no-jira] fix: description  \033[0m"
  exit 1
fi
